---
name:checks  # name shown in github action

on: [push]  #this is the trigger


jobs: 
  test-lint:             #  id of the job
    name: test and lint   # human name seen in github UI
    runs-on : ubuntu-20.04 # we are running job on 

    steps:    #things that are going to run for the job
      - name: Login to Docker Hub   # name of the step used in the GITHUB actions UI 
        uses: docker/login-action@v1 #  ready made docker action for github login/ @v1  version of the action we want to use 
        with: # then we pass the parameters
          username: ${{ secrets.DOCKERHUB_USER  }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: checkout
        uses: actions/checkout@v2  # it checks our code out

      - name : test
        run: docker-compose run --rm app sh -c "python manage.py test"
        
      - name: Linting
        run : docker-compose run --rm app -c "flake8"
